### ISSUE TITLE
write access on zone

### ISSUE THREAD

**Issue by paul-mesnilgrente** [Chralu/gandyn#17]
Hello,

when I execute your 
```bash
sudo /usr/local/bin/gandyn.py --config /home/paul/gandyn/gandyn.conf
```
The log file is giving an error on the last line :
```
Mon, 30 Nov 2015 23:11:45 DEBUG    DNS record IP address : 217.70.184.38
Mon, 30 Nov 2015 23:11:45 DEBUG    Current public IP address : 86.199.105.167
Mon, 30 Nov 2015 23:11:45 ERROR    An error occured using Gandi API : <Fault 581050: "Error on object : OBJECT_ZONE (CAUSE_NORIGHT) [PM13328-GANDI isn't allowed to modify zone 681838]">
```

I am a newbie with dns on gandi, I just acquire a domain with them, I've made this in the dns zone :
- create zone dns named paul-mesnilgrente.com (which is my domain)
- add a line on it
    - name : @
    - Type : A
    - Value : my actual ip

I have activated my prod api too and copy the key in gandyn.conf

Have you got an idea ? I have searched on google but no answers available...

Thank you :)

**Comment by Chralu** [comment]
Hi @paul-mesnilgrente,

it seems you succeed to overcome this issue ?

Cheers,

**Comment by paul-mesnilgrente** [comment]
Yes sorry, I forgot this issue. It was not your fault. In my domain page, the part on "zone files" "can be edited" was on no.
