### ISSUE TITLE
Problem to do the setup install on a synology DS214

### ISSUE THREAD

**Issue by blaisbr** [Chralu/gandyn#6]
When I try to execute the  "python3 setup.py install", I have the following stdout:

running install
running build
running build_py
running build_scripts
running install_lib
byte-compiling /opt/local/lib/python3.2/site-packages/ipretriever/adapter.py to adapter.cpython-32.pyc
Segmentation fault (core dumped)

Do you have any idea?

bruno

**Comment by Chralu** [comment]
Hi @blaisbr,

here is my 1 year late answer :/
It seems there is an issue with your python install. I can't tell you anything better than "try updating your python install".

Cheers,
